/* The Loeb Network: service worker registration + "Get the app" install button.
   Generated by tools/build_site.py; do not edit by hand. */
(function () {
  var script = document.currentScript;
  var root = (script && script.getAttribute("data-root")) || "";

  // 1) Service worker
  if ("serviceWorker" in navigator) {
    window.addEventListener("load", function () {
      navigator.serviceWorker.register(root + "sw.js", { scope: root || "./" }).catch(function () {});
    });
  }

  // 2) Install button
  var standalone = window.matchMedia("(display-mode: standalone)").matches || window.navigator.standalone === true;
  var ua = navigator.userAgent || "";
  var isIOS = /iphone|ipad|ipod/i.test(ua) || (navigator.platform === "MacIntel" && navigator.maxTouchPoints > 1);
  var deferred = null;
  var buttons = Array.prototype.slice.call(document.querySelectorAll(".js-install"));
  var sections = Array.prototype.slice.call(document.querySelectorAll(".js-app-section"));

  function hideAll() {
    buttons.forEach(function (b) { b.hidden = true; });
    sections.forEach(function (s) { s.hidden = true; });
  }
  function show(all) {
    buttons.forEach(function (b) { if (all || !b.classList.contains("js-install-always")) b.hidden = false; });
  }

  if (standalone) { hideAll(); return; }

  function modal(title, html) {
    var old = document.getElementById("app-modal");
    if (old) old.remove();
    var m = document.createElement("div");
    m.id = "app-modal";
    m.className = "app-modal";
    m.setAttribute("role", "dialog");
    m.setAttribute("aria-modal", "true");
    m.setAttribute("aria-labelledby", "app-modal-title");
    m.innerHTML = '<div class="app-modal-box"><button type="button" class="app-modal-close" aria-label="Close">&times;</button>' +
      '<img src="' + root + 'assets/icon-192.png" alt="" width="56" height="56">' +
      '<h3 id="app-modal-title">' + title + "</h3>" + html +
      '<button type="button" class="btn btn-navy app-modal-ok">Got it</button></div>';
    function close() { m.remove(); document.removeEventListener("keydown", esc); }
    function esc(e) { if (e.key === "Escape") close(); }
    m.addEventListener("click", function (e) {
      if (e.target === m || e.target.classList.contains("app-modal-close") || e.target.classList.contains("app-modal-ok")) close();
    });
    document.addEventListener("keydown", esc);
    document.body.appendChild(m);
    m.querySelector(".app-modal-ok").focus();
  }

  function onClick() {
    if (deferred) {
      deferred.prompt();
      deferred.userChoice.then(function (choice) {
        if (choice && choice.outcome === "accepted") hideAll();
        deferred = null;
      });
    } else if (isIOS) {
      modal("Add The Loeb Network to your Home Screen",
        '<p>Tap the Share button <span class="app-share" aria-hidden="true">&#x2191;&#xFE0E;</span>, then <strong>Add to Home Screen</strong>.</p>' +
        '<p class="app-modal-note">Use Safari. If you don’t see the option, scroll down in the Share menu.</p>');
    } else {
      modal("Install The Loeb Network",
        "<p>Open your browser’s menu and choose <strong>Install app</strong> or <strong>Add to Home screen</strong>.</p>" +
        '<p class="app-modal-note">Chrome, Edge and Samsung Internet support installing. On iPhone, use Safari.</p>');
    }
  }
  buttons.forEach(function (b) { b.addEventListener("click", onClick); });

  window.addEventListener("beforeinstallprompt", function (e) {
    e.preventDefault();
    deferred = e;
    show(true);
  });
  window.addEventListener("appinstalled", function () { deferred = null; hideAll(); });

  if (isIOS) show(true);
})();
