/* The Loeb Network service worker. Generated by tools/build_site.py; do not edit by hand. */
const CACHE = "tln-f11175813a";
const CORE = ["./", "index.html", "about.html", "why.html", "services.html", "contact.html", "case-files/index.html", "global-accountability/index.html", "offline.html", "css/styles.css", "js/app.js", "manifest.webmanifest", "assets/tln-crest-112.png", "assets/tln-crest.png", "assets/tln-crest.webp", "assets/favicon-32.png", "assets/icon-192.png", "assets/icon-512.png", "assets/apple-touch-icon.png"];
const OFFLINE = "offline.html";

self.addEventListener("install", (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(CORE)).then(() => self.skipWaiting()));
});

self.addEventListener("activate", (e) => {
  e.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k.startsWith("tln-") && k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener("fetch", (e) => {
  const req = e.request;
  if (req.method !== "GET") return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;
  const isHTML = req.mode === "navigate" || (req.headers.get("accept") || "").includes("text/html");
  if (isHTML) {
    // Network first for pages, falling back to the cached copy, then the offline page.
    e.respondWith(
      fetch(req)
        .then((res) => {
          if (res.ok) { const copy = res.clone(); caches.open(CACHE).then((c) => c.put(req, copy)); }
          return res;
        })
        .catch(() => caches.match(req, { ignoreSearch: true }).then((hit) => hit || caches.match(OFFLINE)))
    );
    return;
  }
  // Static files: serve from cache, refresh in the background.
  e.respondWith(
    caches.match(req).then((hit) => {
      const net = fetch(req).then((res) => {
        if (res.ok) { const copy = res.clone(); caches.open(CACHE).then((c) => c.put(req, copy)); }
        return res;
      }).catch(() => hit);
      return hit || net;
    })
  );
});
